# Generated by Django 4.1.2 on 2022-11-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_materias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grado', models.CharField(max_length=30)),
                ('nombre_profesor_a_cargo', models.CharField(max_length=30)),
                ('apellido_profesor_a_cargo', models.CharField(max_length=30)),
            ],
        ),
    ]
